### ISSUE TITLE
Bug with newHiddenInput

### ISSUE THREAD

**Issue by DrSchizo** [derekpcollins/jquery-custom-select-menu#20] opened 2013-09-04 18:30 UTC
On line 98, the script change the value of newHiddenInput, but this item is only created on line 115. I fixed this issue by moving line 111 to 115 (creation of newList and newHiddenInput) after the line 74 (creation of newContainer).

**Comment by derekpcollins** [comment] 2013-11-02 22:36
This is a duplicate of issue #18 and was fixed when I merged #19.

**Closed as completed by derekpcollins** 2013-11-02 22:36 UTC
